#!/bin/bash
#*******************************************************************************
# Copyright (c) 2012 Sierra Wireless and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#     Guilhem Saurel for Sierra Wireless - initial script
#*******************************************************************************

mkdir -p /opt/mihini
cd /opt/mihini

for rw in persist update apps
do
    mkdir -p /var/opt/mihini/$rw
    ln -s /var/opt/mihini/$rw
done

#useradd -b /opt -U mihini
#chown -R mihini:mihini /{var/,}opt/mihini
